name: app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+57

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_info_plus: ^9.0.2
  upgrader: ^11.3.1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.13.0
  flutter_svg: ^2.0.9
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^19.1.0
  http: ^1.3.0
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  flutter_spinkit: ^5.1.0
  flutter_launcher_icons: any
  easy_localization: ^3.0.0
  intl: 0.19.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  cached_network_image: ^3.2.3
  flutter_swiper_null_safety: ^1.0.2
  page_view_indicators: ^2.0.0
  image_picker: ^0.8.7+4
  mime: ^1.0.0
  permission_handler: ^10.2.0
  socket_io_client: ^2.0.0
  emoji_picker_flutter: ^4.2.0
  in_app_purchase: ^3.2.0
  google_sign_in: ^5.4.0
  reorderables: ^0.4.2
  path_provider: ^2.1.5
  chewie: ^1.4.0
  flutter_image_compress: ^2.4.0
  dio: ^5.3.0
  video_player: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/verificado.png
    - assets/images/google_logo.png
    - assets/images/muscle.svg
    - assets/images/tutorial/es/1.jpg
    - assets/images/tutorial/es/2.jpg
    - assets/images/tutorial/es/3.jpg
    - assets/images/tutorial/es/4.jpg
    - assets/images/tutorial/es/5.jpg
    - assets/images/tutorial/es/6.jpg
    - assets/images/tutorial/en/1.jpg
    - assets/images/tutorial/en/2.jpg
    - assets/images/tutorial/en/3.jpg
    - assets/images/tutorial/en/4.jpg
    - assets/images/tutorial/en/5.jpg
    - assets/images/tutorial/en/6.jpg
    - assets/images/tutorial/it/1.jpg
    - assets/images/tutorial/it/2.jpg
    - assets/images/tutorial/it/3.jpg
    - assets/images/tutorial/it/4.jpg
    - assets/images/tutorial/it/5.jpg
    - assets/images/tutorial/it/6.jpg
    - assets/images/tutorial/fr/1.jpg
    - assets/images/tutorial/fr/2.jpg
    - assets/images/tutorial/fr/3.jpg
    - assets/images/tutorial/fr/4.jpg
    - assets/images/tutorial/fr/5.jpg
    - assets/images/tutorial/fr/6.jpg
    - assets/images/tutorial/de/1.jpg
    - assets/images/tutorial/de/2.jpg
    - assets/images/tutorial/de/3.jpg
    - assets/images/tutorial/de/4.jpg
    - assets/images/tutorial/de/5.jpg
    - assets/images/tutorial/de/6.jpg
    - assets/images/gymswipe_premium.png
    - assets/images/rayo.svg
    - assets/images/default_profile.png
    - assets/translations/
    - assets/images/welcome_bg.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icono.png"
  image_path_ios: "assets/images/icono.png"
