name: app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_swiper_null_safety: ^1.0.2
  page_view_indicators: ^2.0.0
  image_picker: ^0.8.7+4
  mime: ^1.0.0
  socket_io_client: ^2.0.0
  emoji_picker_flutter: ^4.2.0
  in_app_purchase: ^3.2.0
  google_sign_in: ^5.4.0
  reorderables: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google_logo.png
    - assets/images/default_profile.png
