name: app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+24

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_info_plus: ^9.0.2
  upgrader: ^6.3.0
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  flutter_spinkit: ^5.1.0
  flutter_launcher_icons: any
  easy_localization: ^3.0.0
  intl: 0.19.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  cached_network_image: ^3.2.3
  flutter_swiper_null_safety: ^1.0.2
  page_view_indicators: ^2.0.0
  image_picker: ^0.8.7+4
  mime: ^1.0.0
  permission_handler: ^10.2.0
  socket_io_client: ^2.0.0
  emoji_picker_flutter: ^4.2.0
  in_app_purchase: ^3.2.0
  google_sign_in: ^5.4.0
  reorderables: ^0.4.2
  flutter_sound: ^9.25.4
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  audioplayers: ^5.2.1
  record: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google_logo.png
    - assets/images/default_profile.png
    - assets/translations/

flutter_icons:
  android: true
  image_path: "assets/images/icono.png"
